services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        - BACKEND_URI=http://localhost:${BACKEND_PORT}/api
        - SOCKET_MIDDLEWARE_URI=http://localhost:${SOCKET_MIDDLEWARE_PORT}
        - BACKEND_SOCKET_URI=http://localhost:${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - my-network
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - my-network
    environment:
      - FRONTEND_URI=http://frontend:${FRONTEND_PORT}
      - AZURE_TOKEN=${AZURE_TOKEN}
      - AZURE_URL=${AZURE_URL}
      - MONGO_URI=${MONGO_URI}
      - MONGO_LOCAL_URI=${MONGO_LOCAL_URI}

  sockets-middleware:
    container_name: sockets-middleware
    build:
      context: ./middleware
    ports:
      - "${SOCKET_MIDDLEWARE_PORT}:${SOCKET_MIDDLEWARE_PORT}"
    networks:
      - my-network
    depends_on:
      - backend
      - frontend
    environment:
      - BACKEND_URI=http://backend:${BACKEND_PORT}/api

  sockets-jokes:
    container_name: sockets-jokes
    build:
      context: ./sockets-jokes
    networks:
      - my-network
    depends_on:
      - sockets-middleware
    environment:
      - BACKEND_URI=http://backend:${BACKEND_PORT}/api
      - SOCKET_MIDDLEWARE_URI=http://sockets-middleware:${SOCKET_MIDDLEWARE_PORT}

  sockets-weather:
    container_name: sockets-weather
    build:
      context: ./sockets-weather
    networks:
      - my-network
    depends_on:
      - sockets-middleware
    environment:
      - BACKEND_URI=http://backend:${BACKEND_PORT}/api
      - SOCKET_MIDDLEWARE_URI=http://sockets-middleware:${SOCKET_MIDDLEWARE_PORT}

  sockets-open-ai:
    container_name: sockets-open-ai
    build:
      context: ./sockets-open-ai
    networks:
      - my-network
    depends_on:
      - sockets-middleware
    environment:
      - BACKEND_URI=http://backend:${BACKEND_PORT}/api
      - SOCKET_MIDDLEWARE_URI=http://sockets-middleware:${SOCKET_MIDDLEWARE_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

networks:
  my-network:
    driver: bridge
