apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: sockets-middleware
  name: sockets-middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sockets-middleware
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: sockets-middleware
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: env
            - secretRef:
                name: app-secrets
          image: lucasremigio/chatbot-middleware:latest
          name: sockets-middleware
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
