apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-cronjob
spec:
  # Run every day at 2:00 AM
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-cron
              image: docker.io/projetocn/projeto-cn-backup-cron:production
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: env-configmap
          imagePullSecrets:
            - name: regcred
          restartPolicy: OnFailure
